export const AUTHSTART="AUTHSTART";
export const AUTHSUCCESS="AUTHSUCCESS";
export const AUTHFAIL="AUTHFAIL";
export const AUTHLOGOUT="AUTHLOGOUT";
export const SETAUTHREDIRECTPATH="SETAUTHREDIRECTPATH";